### ISSUE TITLE
New CSSE data 2020-03-16

### ISSUE THREAD

**Issue by zuphilip** [nicebread/corona#12]
There is new data available from https://github.com/CSSEGISandData/COVID-19/tree/master/csse_covid_19_data/csse_covid_19_time_series . Can you restart the app to make them available?

For more automated state: Can you configure the app on shinyapps.org such that it will restart automatically say every 3h?

**Comment by nicebread** [comment]
A restart triggered the download, so this is principally working. I'll look into this today.
