### ISSUE TITLE
Cumulative cases per population density

### ISSUE THREAD

**Issue by tkappen** [nicebread/corona#13]
Awesome graph! It is my to go to on a daily basis to understand the spread better.
Looking at the differences by country, the cumulative cases per 100.000 inhabitants do not always make sense to me. This population size is very dependent on where you draw the border line and the virus is not restricted to border lines per se. Simply taking the cumulative cases also seems wrong. Wouldn't it help to plot the cumulative cases per population density? That is a characteristic that is truly related to the spread of the virus. 

I would have suggested a change in code myself, but it is a bit chaotic in our hospital. That's why I am only posting this as an idea, sorry.

Kind regards
Teus

**Comment by nicebread** [comment]
Interesting suggestion; I haven't seen such a plot yet.

One potential problem: We only have data on national level (for some countries, such as USA, on state level). But the population density varies a lot within country, I guess much more than between countries. So I fear that adjusting for national population density doesn't really work. 

Probably this is more a suggestion for a map-based visualization?

**Comment by tkappen** [comment]
Sorry for the delay. I work as a physician in the hospital, and we are reverting our operating theater complex to an ICU, which kept me occupied (and probably will for quite some time more).

True, that does complicate things. The world data bank does have the rural land area and population, and the urban land area and population. So we could calculate the rural population density and the urban population density to get a feel for the distribution over the country. But without Covid-19 data on that same level, it is not that helpful.

Not sure about the map though. I think the population density should have the strongest relationship over time in the growth rate of developing cases. In a country with a higher population density R0 is expected to be higher, so if you want to have a feel for which country is doing better than it is the one with the lowest R0 in respect to the population density (and other factors of course).

Still loving your plot though. I check almost every day.

**Comment by nicebread** [comment]
> Sorry for the delay. I work as a physician in the hospital, and we are reverting our operating theater complex to an ICU, which kept me occupied (and probably will for quite some time more).

Thanks for your work!!! This is so important.

I'm closing this issue for now. Although I like your idea, and the information certainly would be interesting, I don't think it can be accomodated within the design of this app.
