### ISSUE TITLE
cumulative deaths per 100000 capita

### ISSUE THREAD

**Issue by Olifair** [nicebread/corona#14]
Hello, thanks a lot for this app, just what I needed to get a better picture. It's also great to have added the cumulative deaths, however it would be great if you could consider (as you have already the data ;.) to add also deaths per 100000 capita 
Cheers

**Comment by nicebread** [comment]
Done, implement in 331ef60dac2cd7bcef6ffd9eb6befe97644dbc17, and already online!

**Comment by Olifair** [comment]
Wow, great, thanks a lot, that was rapid.
