### ISSUE TITLE
Download plot function: implement new plot features in .Rmd

### ISSUE THREAD

**Issue by nicebread** [nicebread/corona#16]
Angelika, if you find the time, can you update the download functionality? The plot has changed a bit (mostly the new target variables, and the US states plot), and I think the .Rmd must be adjusted accordingly.

**Comment by astefan1** [comment]
Sure! I'll update it right away :)

**Comment by astefan1** [comment]
Done :) I updated the plot functionality.
I accidentally committed directly to the Master (actually I wanted to do a pull request first but then I forgot about it - I will do that again next time!). I hope this didn't create any troubles 😞

**Comment by nicebread** [comment]
Nice! It's online.
