### ISSUE TITLE
Add the url to the online shiny app as website on top

### ISSUE THREAD

**Issue by zuphilip** [nicebread/corona#2]
I suggest to also add the url to the [online shiny app](http://shinyapps.org/apps/corona/) as the website on the top:

![github-website](https://user-images.githubusercontent.com/5199995/76678095-59f6b000-65d5-11ea-881b-f624ba62f9de.jpg)

Also some suitable topics might help the discoverability of this repo.

**Comment by zuphilip** [comment]
Maybe also be more precise in the description that this is a "Visualization of Covid-19 **confirmed** cases".

**Comment by nicebread** [comment]
Good points! Done.

**Comment by zuphilip** [comment]
Thank you!
