### ISSUE TITLE
Missing countries

### ISSUE THREAD

**Issue by AmelieGourdonKanhukamwe** [nicebread/corona#23]
Hi Felix,

US and UK not showing anymore; I also seem to remember there were other countries after this, so maybe an issue with the length of the country list?
![image](https://user-images.githubusercontent.com/11824414/76969008-ba615680-6921-11ea-907f-750ec1c03072.png)
Thanks for all your wok in this!

**Comment by nicebread** [comment]
Fixed - this was caused by a change in data format for th ECDC data.

**Comment by AmelieGourdonKanhukamwe** [comment]
Thanks!
