### ISSUE TITLE
Slider "Offset at start" should start at 1 not 0

### ISSUE THREAD

**Issue by knbknb** [nicebread/corona#26]
When you set the y axis to logarithmic, (= set checkbox " Print y-axis as log scale")
 and set the slider "Offset at start" to its lowermost value possible, 0,

the plot disappears and an error occurs: "Error: non-finite location and/or size for viewport"

Perhaps Slider "Offset at start" shoud start at 1 not 0 in order to avoid NaN error, or something like that.

**Comment by nicebread** [comment]
Fixed, thanks for the note!
