### ISSUE TITLE
Y-axis labels

### ISSUE THREAD

**Issue by astefan1** [nicebread/corona#27]
I received the feedback that the y-axis in the "Confirmed cumulative cases/deaths per 100,000" option is misleading. It seems to suggest that the case numbers are simply divided by 100,000. I agree with this feedback. 

One option that was suggested was to call it "Confirmed cumulative cases/deaths per capita (adjusted)" and explain in a footnote that "adjusted" means multiplied by 100,000. I think this would make it clearer. What do you think?

**Comment by nicebread** [comment]
Thanks for the PR - merged and online!
