### ISSUE TITLE
R function for ordinal numbers

### ISSUE THREAD

**Issue by larsvilhuber** [nicebread/corona#29]
When choosing "1" as the nth case, it's not ... "th". The first three in English are different. Is there a function in R? 
![image](https://user-images.githubusercontent.com/7022712/77238087-e55add00-6ba3-11ea-82e6-4b692f1ceb26.png)

**Comment by nicebread** [comment]
Good point. Fixed; now there is a function:

```
get_nth_label <- function(x) {
	if (x==1) {
		return("1st")
	} else if (x==2) {
		return("2nd")
	} else if (x==3) {
		return("3rd")
	} else if (x > 3) {
		return(paste0(x, "th"))
	} else {
		return("Error")
	}
}
```
