### ISSUE TITLE
Trying to run app in Australia

### ISSUE THREAD

**Issue by deborahapthorp** [nicebread/corona#31]
Hi Felix, 

I love the Shiny app and have been trying all day to get it to work on my computer. It gets as far as generating the UI, but then I get this error message: 

Warning: Error in : Can't rename columns that don't exist.
x The column `Countries and territories` doesn't exist.
  80: <Anonymous>
Error : Can't rename columns that don't exist.
x The column `Countries and territories` doesn't exist.

I think it might be an issue with being in Australia, so that today <- Sys.Date() produces a date ahead of the actual data, but hacking this to today <- Sys.Date() -1 doesn't seem to fix the problem. 

Any clues would be great! I'm not super experienced with Shiny. 

Best

Deborah.

**Comment by nicebread** [comment]
Hi Derborah,

the error happens because ECDC changed its data format. I will upload a much improved version of the app today; here is a preview: http://shinyapps.org/apps/corona_dev/

Australia should work there.

Best

**Comment by deborahapthorp** [comment]
Hi Felix, 

Ah, I thought it might be that! 

I can’t see the dev repository on your GitHub - guessing it’s not public yet? Currently it’s working but not starting from 100 days when I try to plot cumulative cases per capita, perhaps you’re still working on it? 

Cheers

Deborah.

**Comment by nicebread** [comment]
The new code is in the https://github.com/nicebread/corona/tree/mixed-effects-fit branch. I plan to merge it into the master today, and to release the new version of the online app.

**Comment by deborahapthorp** [comment]
Fantastic, thank you! I love all your apps and use them in my teaching. The p-hacker one in particular is brilliant!

Best

Deborah.
